version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.12.1
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.12.1
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  test-runner:
    build:
      context: .
    container_name: test-runner
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    command: >
      sh -c "sleep 10 && mvn clean test"
